
library(shiny)
library(shinyWidgets)
library(shinydashboard)
library(shinydashboardPlus)
library(haven)
library(ggplot2)
library(modeest)
library(plotly)
library(ca)
library(rjson)
library(stringr)
library(highcharter)
library(factoextra)
library(FactoMineR)
library(MASS)
library(philentropy)
library(ggrepel)
